### ISSUE TITLE
Don't depend on pwd

### ISSUE THREAD

**Issue by wellle** [adjust/elastex#1]
Currently elastex only works in directories that contain a config.yml. To make it work everywhere there are a couple of possible solutions:
- try in this order: `./.elastexrc`, `~/.elastexrc`, `/etc/elastexrc`
- add flag `--config myconfigfile`
- use a environment variable like `$ELASTEXRC`

**Comment by ferki** [comment]
The configuration behaviour is now documented on the (Configuring elastex)[https://github.com/adjust/elastex/wiki/Configuring-elastex] wiki page.

Note: for now it still tries to look for `./config.yml` first for backwards compatibility, but we can deprecate that in favor of `./.elastexrc`.
